### ISSUE TITLE
Error during Database Setup

### ISSUE THREAD

**Issue by bocajspear1** [GhostManager/Ghostwriter#121]
Using commit 7d62d1ae180617a. 

Ran the command to populate the models and got this error:

```
$ docker-compose -f local.yml run --rm django /seed_data
Creating ghostwriter_django_run ... done
PostgreSQL is available
Loading /app/ghostwriter/reporting/fixtures/initial.json...
Installed 12 object(s) from 1 fixture(s)
Loading /app/ghostwriter/rolodex/fixtures/initial.json...
Installed 10 object(s) from 1 fixture(s)
Loading /app/ghostwriter/shepherd/fixtures/initial.json...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "shepherd_whoisstatus" does not exist
LINE 1: UPDATE "shepherd_whoisstatus" SET "whois_status" = 'Enabled'...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/app/ghostwriter/shepherd/fixtures/initial.json': Could not load shepherd.WhoisStatus(pk=1): relation "shepherd_whoisstatus" does not exist
LINE 1: UPDATE "shepherd_whoisstatus" SET "whois_status" = 'Enabled'...
```

**Comment by chrismaddalena** [comment]
Hey @bocajspear1, we took some steps to minimize these sorts of hiccups in the latest release. There were some problems with migrations if you were setting up a fresh install vs. updating an existing install.

If migrations run first, the database should be setup for you to add the seed data.

**Comment by noraj** [comment]
I have those errors instead with V2.0 commit 124a9f71977a8f5f03c8a99854fa9ddd5b69de72:

```
$ sudo docker-compose -f local.yml run --rm django /seed_data
[sudo] password for noraj: 
Creating ghostwriter_django_run ... done
PostgreSQL is available
Loading /app/ghostwriter/shepherd/fixtures/initial.json...
Installed 27 object(s) from 1 fixture(s)
Loading /app/ghostwriter/rolodex/fixtures/initial.json...
Installed 10 object(s) from 1 fixture(s)
Loading /app/ghostwriter/reporting/fixtures/initial.json...
INFO 2020-12-01 16:00:14,543 signals 16 139867692490056 Template file change detected, so starting linter
INFO 2020-12-01 16:00:14,543 signals 16 139867692490056 Linting newly uploaded template: /app/ghostwriter/media/templates/template.docx
ERROR 2020-12-01 16:00:14,544 reportwriter 16 139867692490056 Template file path did not exist: /app/ghostwriter/media/templates/template.docx
INFO 2020-12-01 16:00:14,544 reportwriter 16 139867692490056 Template linting completed
INFO 2020-12-01 16:00:14,546 signals 16 139867692490056 Template file change detected, so starting linter
INFO 2020-12-01 16:00:14,546 signals 16 139867692490056 Linting newly uploaded template: /app/ghostwriter/media/templates/template.pptx
ERROR 2020-12-01 16:00:14,546 reportwriter 16 139867692490056 Template file path did not exist: /app/ghostwriter/media/templates/template.pptx
INFO 2020-12-01 16:00:14,547 reportwriter 16 139867692490056 Template linting completed
Installed 16 object(s) from 1 fixture(s)
```

**Comment by chrismaddalena** [comment]
Yeah, this is sort of a bug / documentation issue. The database loaded without any issue. The template linter generated those errors and warnings. The templates loaded into the database didn't exist on disk, so the linting failed.

The templates did not exist because they won't be moved to _/app/ghostwriter/media/templates_ until `docker-compose` executes the _start_ script. The _start_ script copies the default templates into that directory. So, everything works if you build the containers and launch Ghostwriter at least one time. The files will be in the right place for the linter to find them when you seed the database.

Try this:

1. Build and start the containers: `docker-compose -f local.yml stop; docker-compose -f local.yml rm -f; docker-compose -f local.yml build; docker-compose -f local.yml up -d`

2. Once everything is loaded, try seeding the database: `docker-compose -f local.yml run --rm django /seed_data`

Replace `local.yml` with `production.yml` if you're going into prod or testing with HTTPS.
