### ISSUE TITLE
Channels dependencie issue

### ISSUE THREAD

**Issue by Siryu6** [GhostManager/Ghostwriter#125]
Hi !
Fist thanks for this awesome project !
I'm having an issue building the django and queue containers.
 Both are missing "**channels**" module when i'm running ```docker-compose -f local.yml up -d```.
I tried to debug it without success since i'm not really familiar to _docker-compose_ but **channels** is listed in requirements/base.txt and shouldn't be missing ?

```bash
$ sudo docker-compose -f local.yml up -d                            
Creating ghostwriter_postgres_1 ... done
Creating ghostwriter_redis_1    ... done
Creating ghostwriter_django_1   ... done
Creating ghostwriter_queue_1    ... done
$ sudo docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS               NAMES
bfa7c81b01c2        ghostwriter_local_queue           "/entrypoint /start-…"   14 seconds ago      Exited (1) 11 seconds ago                       ghostwriter_queue_1
1cd06416e78a        ghostwriter_local_django          "/entrypoint /start"     14 seconds ago      Exited (1) 11 seconds ago                       ghostwriter_django_1
06809f5fe245        redis:5-alpine                    "docker-entrypoint.s…"   14 seconds ago      Up 13 seconds               6379/tcp            ghostwriter_redis_1
7cbda3c7f116        ghostwriter_production_postgres   "docker-entrypoint.s…"   14 seconds ago      Up 13 seconds               5432/tcp            ghostwriter_postgres_1
$ sudo docker logs 1cd06416e78a
PostgreSQL is available
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'channels'
$ sudo docker logs bfa7c81b01c2
PostgreSQL is available
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'channels'
```

**Comment by Siryu6** [comment]
Nvm. 
Blame is on me.
