### ISSUE TITLE
Cant install 2.2.3: Cant create superuser: null value in column "role"

### ISSUE THREAD

**Issue by dobin** [GhostManager/Ghostwriter#201]
I follow the steps in the installation manual, but cant create a superuser:

```
WARNING: Found orphan containers (graphql) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating ghostwriter_redis_1    ... done
Creating ghostwriter_postgres_1 ... done
Creating ghostwriter_django_1   ... done
Creating ghostwriter_queue_1    ... done
root@vectr:/opt/Ghostwriter# docker-compose -f local.yml run --rm django /seed_data
WARNING: Found orphan containers (graphql) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting ghostwriter_postgres_1 ... done
PostgreSQL is available
Loading /app/ghostwriter/shepherd/fixtures/initial.json...
Installed 27 object(s) from 1 fixture(s)
Loading /app/ghostwriter/rolodex/fixtures/initial.json...
Installed 14 object(s) from 1 fixture(s)
Loading /app/ghostwriter/reporting/fixtures/initial.json...
INFO 2022-03-16 10:44:40,356 signals 16 140139053763400 Template file change detected, so starting linter
INFO 2022-03-16 10:44:40,356 signals 16 140139053763400 Linting newly uploaded template: /app/ghostwriter/media/templates/template.docx
ERROR 2022-03-16 10:44:40,358 reportwriter 16 140139053763400 Template file path did not exist: /app/ghostwriter/media/templates/template.docx
INFO 2022-03-16 10:44:40,358 reportwriter 16 140139053763400 Template linting completed
INFO 2022-03-16 10:44:40,363 signals 16 140139053763400 Template file change detected, so starting linter
INFO 2022-03-16 10:44:40,363 signals 16 140139053763400 Linting newly uploaded template: /app/ghostwriter/media/templates/template.pptx
ERROR 2022-03-16 10:44:40,363 reportwriter 16 140139053763400 Template file path did not exist: /app/ghostwriter/media/templates/template.pptx
INFO 2022-03-16 10:44:40,363 reportwriter 16 140139053763400 Template linting completed
Installed 16 object(s) from 1 fixture(s)
root@vectr:/opt/Ghostwriter# docker-compose -f local.yml run --rm django python manage.py createsuperuser
WARNING: Found orphan containers (graphql) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting ghostwriter_postgres_1 ... done
PostgreSQL is available
Username: admin
Email address: asdf@asdf.com
Password: 
Password (again): 
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "role" violates not-null constraint
DETAIL:  Failing row contains (1, argon2$argon2id$v=19$m=102400,t=2,p=8$WnN6Y1FBMGJ3VGJzOFhSYVJJYl..., null, t, admin, asdf@asdf.com, t, t, 2022-03-16 10:45:38.20464+00, , null, America/Los_Angeles, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "manage.py", line 31, in <module>
   execute_from_command_line(sys.argv)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
   utility.execute()
 File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
   return super().execute(*args, **options)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
   output = self.handle(*args, **options)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
   self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 163, in create_superuser
   return self._create_user(username, email, password, **extra_fields)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 146, in _create_user
   user.save(using=self._db)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
   super().save(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
   self.save_base(using=using, force_insert=force_insert,
 File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
   updated = self._save_table(
 File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
   results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
 File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
   return manager._insert(
 File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
   return query.get_compiler(using=using).execute_sql(returning_fields)
 File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
   cursor.execute(sql, params)
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
   return super().execute(sql, params)
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
   return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
   return executor(sql, params, many, context)
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
 File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
   raise dj_exc_value.with_traceback(traceback) from exc_value
 File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "role" violates not-null constraint
DETAIL:  Failing row contains (1, argon2$argon2id$v=19$m=102400,t=2,p=8$WnN6Y1FBMGJ3VGJzOFhSYVJJYl..., null, t, admin, asdf@asdf.com, t, t, 2022-03-16 10:45:38.20464+00, , null, America/Los_Angeles, null).
```

**Comment by dobin** [comment]
I tried it again from scratch, without first using the user "admin". Worked this time.

**Comment by dobin** [comment]
I tried it again again, as I am still unable to get Ghostwriter to work. Following the installation manual closely, the same error appeared...

**Comment by dobin** [comment]
I just throw away the container, and do all the steps one after another from the install, hoping it works. It once worked.
