### ISSUE TITLE
Updating Project Duration Fails when no Slack Channel is set

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#261]
When I try to update the end-date of a project that has no slack channel set, Ghostwriter refuses to save the project, but does not generate an error-message.

**To Reproduce**
1. Have GW configured with slack integration
2. Create a project without a slack channel
3. Checkout a domain to that project (not sure this is needed)
4. Save the project.
5. Edit the project and update the end-date

Docker logs show:
```
NFO 2022-10-27 11:28:20,214 signals 18 139944830729016 Project dates have changed so adjusting domain and server checkouts
INFO 2022-10-27 11:28:20,216 signals 18 139944830729016 Start date changed by 0 days
INFO 2022-10-27 11:28:20,216 signals 18 139944830729016 End date changed by 1 days
ERROR 2022-10-27 11:28:20,217 views 18 139944830729016 Failed to update the project
Traceback (most recent call last):
  File "/app/./ghostwriter/rolodex/views.py", line 1456, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/./ghostwriter/rolodex/signals.py", line 133, in update_project
    if slack.enabled and instance.slack_channel:
UnboundLocalError: local variable 'slack' referenced before assignment
```

**Expected Behavior**
Projects save normally, notification sent to general slack channel.

**Server Specs:**
 - OS: Ubuntu 20.04.4 LTS
 - Docker: Docker version 20.10.17, build 100c701
 - Ghostwriter v3.1.1, released 18 October 2022

**Comment by er4z0r** [comment]
I've had a look at the signals.py code. It seems that the `slack` variable is indeed [only set,](https://github.com/GhostManager/Ghostwriter/blob/59f45189914f82471e72c5a7434186de6ddb3375/ghostwriter/rolodex/signals.py#L45) if the project as an associated slack channel.

**Comment by chrismaddalena** [comment]
Thanks for reporting this! I was trying to avoid an unnecessary db query, but it did lead to a situation where the signal tries to check the Slack config and the config isn't set. It's an easy fix that will be in a release later today and turn this bug into a ghost for Halloween.

The release also includes an updated Ghostwriter CLI that will seed the database when you run `contianers build`. That should address the problem we talked about in Slack where updated default values need to be manually loaded following a Ghostwriter upgrade 😃

**Comment by er4z0r** [comment]
So that's 2/2 of my requests fixed in one day? Awesome!
