### ISSUE TITLE
Forgot Password is Broken

### ISSUE THREAD

**Issue by ArgentEnergy** [GhostManager/Ghostwriter#293]
On the login page, click the Forgot password link. Enter a valid email address. A 500 error will be returned.

```
ERROR 2023-03-07 14:58:24,696 log 22 139623559428920 Internal Server Error: /accounts/password/reset/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/account/views.py", line 105, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python3.10/site-packages/allauth/account/views.py", line 698, in form_valid
    form.save(self.request)
  File "/usr/local/lib/python3.10/site-packages/allauth/account/forms.py", line 541, in save
    self._send_password_reset_mail(request, email, self.users, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/account/forms.py", line 581, in _send_password_reset_mail
    get_adapter(request).send_mail(
  File "/usr/local/lib/python3.10/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg.send()
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base.py", line 94, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base_requests.py", line 58, in _send
    return super()._send(message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base.py", line 124, in _send
    response = self.post_to_esp(payload, message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base_requests.py", line 80, in post_to_esp
    self.raise_for_status(response, payload, message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/mailgun.py", line 62, in raise_for_status
    super().raise_for_status(response, payload, message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base_requests.py", line 91, in raise_for_status
    raise AnymailRequestsAPIError(
anymail.exceptions.AnymailRequestsAPIError: Mailgun API response 404 (Not Found): '404 page not found\n'
```

I also didn't see any option in the Admin panel where you could configure mail server settings in the event someone wants to use an internal SMTP server.

This is happening on the latest version.

**Comment by ArgentEnergy** [comment]
@chrismaddalena Understood. Thank you for the clarification.
