### ISSUE TITLE
500 Internal Server Error When Uploading Screenshot

### ISSUE THREAD

**Issue by brewballs** [GhostManager/Ghostwriter#303]
**Describe the bug**
I receive a 500 Internal Server Error whenever I attempt to upload a screenshot. This happens if I upload on the report page by clicking the paper clip or on a findings page.

**To Reproduce**
1. Go to an active report click the paper clip icon to attach screenshot to a finding. Add friendly name and caption. Happens with both browse or drag and drop. 
2. Click on submit
3. Get 500 Internal Server Error page

django code error

`ERROR 2023-04-03 12:05:35,337 log 14 140134473243448 Internal Server Error: /reporting/reports/evidence/upload/76
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/app/./ghostwriter/reporting/views.py", line 2287, in form_valid
    self.object.save()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/./ghostwriter/reporting/signals.py", line 84, in evidence_update
    new = current.replace(prev_friendly, friendly)
AttributeError: 'NoneType' object has no attribute 'replace'
INFO:     172.18.0.6:40752 - "POST /reporting/reports/evidence/upload/76 HTTP/1.0" 500 Internal Server Error`

**Expected Behavior**
File uploaded without the 500 error. 

**Server Specs:**
 - OS: Ubuntu 22.04.2 LTS \n \l
 - `Linux 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 -` Docker Docker version 20.10.17, build 100c70180f `
 -`/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
docker-compose version 1.29.2, build unknown`
 - Ghostwriter v3.2.5, released 31 March 2023

**Additional context**
I recently upgraded Debian (just ran apt get update && apt get upgrade) and GhostWriter.

**Comment by er4z0r** [comment]
The code causing this seems to be [here](https://github.com/GhostManager/Ghostwriter/blob/master/ghostwriter/reporting/signals.py#L83).
Not exactly sure what it does but it seems to be constructing some kind of link and failing to do so in this particular case.

**Comment by ArgentEnergy** [comment]
I'm also running into this issue and it's blocking us from upgrading to the latest version.

**Comment by brewballs** [comment]
@ArgentEnergy there is a work around for this. Open the finding, click save, and the problem goes away. There is more info in a dialogue in the BloodHound slack.

**Comment by pwnl337** [comment]
This also happens when uploading a txt file as evidence.

**Comment by chrismaddalena** [comment]
I'm back from vacation and have this resolved for a release this week. Sorry for the inconvenience!

From the Slack convo last week:

> Thanks for raising the issue. The problem occurs when Ghostwriter tries to replace the evidence item's name in the associated finding. This is a recent change to help you when you change the name, so you don't need to update references in the finding.
> 
> My guess is there is an empty field in the finding, and there needs to be a check added to make sure the field didn't return `None`. I thought the test case checked for that, and empty fields returned "", an empty string, but maybe that's not true for all of them.
> 
> It's an edge case. If the finding has not been edited, a blank field is `None` in the database. After being saved once, blank fields become "" because of how the editor works. It should be an easy fix.
> 
> I'm out this week, but I'll check this today to verify and submit the change.

The above was accurate, and I have the issue resolved and a regression test in place.

**Comment by chrismaddalena** [comment]
This is live in v3.2.6.
