### ISSUE TITLE
Django fails to start after upgrade from 3.2.9

### ISSUE THREAD

**Issue by spankywetfish** [GhostManager/Ghostwriter#361]
After updating from v3.2.9 the django container (and therefore the queue container) failed to start correctly.

The log output was as follows...

```
PostgreSQL is available
Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings/production.py", line 1, in <module>
    from .base import *  # noqa
  File "/app/config/settings/base.py", line 267, in <module>
    SESSION_COOKIE_AGE = env("DJANGO_SESSION_COOKIE_AGE", default=60 * 60 * 2)
  File "/usr/local/lib/python3.10/site-packages/environ/environ.py", line 198, in __call__
    return self.get_value(
  File "/usr/local/lib/python3.10/site-packages/environ/environ.py", line 414, in get_value
    value = self.parse_value(value, cast)
  File "/usr/local/lib/python3.10/site-packages/environ/environ.py", line 473, in parse_value
    value = cast(value)
ValueError: invalid literal for int() with base 10: ''
```

Workaround was to remove/comment line 36 
`      - DJANGO_SESSION_COOKIE_AGE=${DJANGO_SESSION_COOKIE_AGE}`
from production.yml

May just be something peculiar to my instance.

cheers

**Comment by chrismaddalena** [comment]
Hey @spankywetfish, I suspect you don't have a value for `DJANGO_SESSION_COOKIE_AGE` in your DotEnv (`.env`) configuration file. Ghostwriter CLI adds that variable with a default value if it is missing. That happens whenever you run Ghostwriter CLI.

If you run `./ghostwriter-cli containers build` you should get the latest v4 containers and your DotEnv will have the necessary values.

**Comment by spankywetfish** [comment]
Hey Chris, adding `DJANGO_SESSION_COOKIE_AGE="7200"` to the `.env` file was the first thing it tried on my troubleshooting journey. It made zero difference.

**Comment by chrismaddalena** [comment]
The default value is `DJANGO_SESSION_COOKIE_AGE='28800'`. Your `7200` is also valid. Which version of Docker and Docker Compose do you have? Older versions do not handle quotes in DotEnv files and try to interpret `"7200"` as a string, not an integer.

You need at least v1.26: `docker-compose --version`

**Comment by spankywetfish** [comment]
I set the value based on the error message `default=60 * 60 * 2`. 
I did try setting it to `="7200"` , `='7200'` and `=7200`, none worked.
I'll check the compose version in the AM

**Comment by spankywetfish** [comment]
`Docker Compose version v2.9.0`

**Comment by chrismaddalena** [comment]
That's an older version from August 2022, but I think it should work for Ghostwriter. There were some changes to `.env` handling in v2.11+ (the latest is v2.23), but nothing that seems to affect this value.

Give this a try:

1. Open `config/settings/base.py`
2. Add this above line 267: `print(env("DJANGO_SESSION_COOKIE_AGE"))`
3. Run this command: `docker compose -f production.yml up --build`
4. Wait to see output from the Django container

The output will look something like this:

```
ghostwriter-django-1          | INFO:     Started reloader process [12] using WatchFiles
ghostwriter-django-1          | 28800
ghostwriter-django-1          | INFO:     Started server process [14]
```

What value is printed? It should be whatever value you have set for `DJANGO_SESSION_COOKIE_AGE` in your `.env` config file.

**Comment by spankywetfish** [comment]
`ghostwriter-django-1          | 7200`

**Comment by chrismaddalena** [comment]
I'm glad to hear that. Ghostwriter CLI runs `docker compose -f production.yml build` so the results should be the same. That's a tough one. It seems like there was an issue with the value that got corrected along the way.
