### ISSUE TITLE
Workflow step "Build environment" fails

### ISSUE THREAD

**Issue by domwhewell-sage** [GhostManager/Ghostwriter#488]
**Describe the bug**
The workflow step "Build environment" is failing in my fork. Specifically the command `./ghostwriter-cli-linux install --dev`. The failure is `ModuleNotFoundError: No module named 'setuptools.command.test'` and I cant see the setuptools version being specified in requirements.txt so I believe it will affect all new installations.

A new version of [setuptools](https://pypi.org/project/setuptools/) was released recently which I think is the cause of the failure. I think it's this [commit](https://github.com/pypa/setuptools/commit/b5bd38edc1cec78b6c1baca047aebf23c6635a48)
I have put the full extract of the workflow log below

**To Reproduce**
1. Run `workflow.yml` or `./ghostwriter-cli-linux install --dev` manually

**Log Extract**
```python
2024-07-29T08:08:18.8646232Z #25 16.66 Collecting setuptools
2024-07-29T08:08:18.8647799Z #25 16.71   Downloading setuptools-72.0.0-py3-none-any.whl (2.3 MB)
2024-07-29T08:08:18.8649220Z #25 16.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 62.3 MB/s eta 0:00:00
{..truncated}
2024-07-29T08:08:51.3408614Z #27 27.74 Collecting autobahn>=0.18 (from daphne<4,>=3.0->channels==3.0.5->-r /requirements/./base.txt (line 19))
2024-07-29T08:08:51.3413195Z #27 27.75   Downloading autobahn-23.6.2.tar.gz (480 kB)
2024-07-29T08:08:51.4911925Z #27 27.86   Preparing metadata (setup.py): started
2024-07-29T08:08:51.9111240Z #27 28.43   Preparing metadata (setup.py): finished with status 'error'
2024-07-29T08:08:52.0440329Z #27 28.44   error: subprocess-exited-with-error
2024-07-29T08:08:52.0441226Z #27 28.44   
2024-07-29T08:08:52.0442363Z #27 28.44   × python setup.py egg_info did not run successfully.
2024-07-29T08:08:52.0443334Z #27 28.44   │ exit code: 1
2024-07-29T08:08:52.0444066Z #27 28.44   ╰─> [6 lines of output]
2024-07-29T08:08:52.0444838Z #27 28.44       Traceback (most recent call last):
2024-07-29T08:08:52.0445690Z #27 28.44         File "<string>", line 2, in <module>
2024-07-29T08:08:52.0446959Z #27 28.44         File "<pip-setuptools-caller>", line 34, in <module>
2024-07-29T08:08:52.0448573Z #27 28.44         File "/tmp/pip-install-829gbreb/autobahn_728e3cd9d30c4f5a88957173081b0c27/setup.py", line 32, in <module>
2024-07-29T08:08:52.0450078Z #27 28.44           from setuptools.command.test import test as test_command
2024-07-29T08:08:52.0451628Z #27 28.44       ModuleNotFoundError: No module named 'setuptools.command.test'
2024-07-29T08:08:52.0452722Z #27 28.44       [end of output]
2024-07-29T08:08:52.0453331Z #27 28.44   
2024-07-29T08:08:52.0454399Z #27 28.44   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-07-29T08:08:52.0455730Z #27 28.56 error: metadata-generation-failed
2024-07-29T08:08:52.0456489Z #27 28.56 
2024-07-29T08:08:52.0458325Z #27 28.56 × Encountered error while generating package metadata.
2024-07-29T08:08:52.0460036Z #27 28.56 ╰─> See above for output.
2024-07-29T08:08:52.0460825Z #27 28.56 
2024-07-29T08:08:52.0461802Z #27 28.56 note: This is an issue with the package mentioned above, not pip.
2024-07-29T08:08:52.0462758Z #27 28.56 hint: See above for details.
2024-07-29T08:08:53.2836111Z #27 ERROR: process "/bin/sh -c pip install --no-cache-dir -r /requirements/local.txt" did not complete successfully: exit code: 1
2024-07-29T08:08:53.2901024Z 2024/07/29 08:08:53 Error trying to build with local.yml: exit status 17
```

**Comment by domwhewell-sage** [comment]
Version 72.0.0 of setup tools did have an issue but it has been yanked from the pypi repo and a new version has been released v72.1.0 which does not have this issue

https://github.com/pypa/setuptools/issues/4518
