### ISSUE TITLE
Failed to generate the Word report: 'NoneType' object has no attribute 'add_run'

### ISSUE THREAD

**Issue by kkirsche** [GhostManager/Ghostwriter#63]
```
ERROR 2020-03-09 18:01:52,444 log 13 139773665434952 Internal Server Error: /reporting/reports/6/generate_docx/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/ghostwriter/reporting/views.py", line 577, in generate_docx
    docx = spenny.generate_word_docx()
  File "/app/ghostwriter/modules/reportwriter.py", line 1312, in generate_word_docx
    report_json)
  File "/app/ghostwriter/modules/reportwriter.py", line 757, in process_text_xml
    self.process_inline_text(line, p)
  File "/app/ghostwriter/modules/reportwriter.py", line 489, in process_inline_text
    run = p.add_run()
AttributeError: 'NoneType' object has no attribute 'add_run'
```

When there is an inline `<code>` section in the findings

**Comment by chrismaddalena** [comment]
This issue has been addressed with #66. More information in this comment:

[https://github.com/GhostManager/Ghostwriter/issues/60#issuecomment-610172741](https://github.com/GhostManager/Ghostwriter/issues/60#issuecomment-610172741)
