### ISSUE TITLE
DNS Record update fails for records > 500 characters

### ISSUE THREAD

**Issue by lez0sec** [GhostManager/Ghostwriter#72]
### Description 
When using the DNS record update function in the Domain Update Controls, I get the following error:

```
Error: value too long for type character varying(500) : Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) psycopg2.errors.StringDataRightTruncation: value too long for type character varying(500) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 381, in worker res = f(*task['args'], **task['kwargs']) File "/app/ghostwriter/shepherd/tasks.py", line 373, in update_dns domain_instance.save() File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save force_update=force_update, update_fields=update_fields) File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base force_update, using, update_fields, File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table forced_update) File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update return filtered._update(values) > 0 File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update return query.get_compiler(self.db).execute_sql(CURSOR) File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql cursor = super().execute_sql(result_type) File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute return super().execute(sql, params) File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers return executor(sql, params, many, context) File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) django.db.utils.DataError: value too long for type character varying(500)
```
### Cause
This is due to the DNS records (including the TXT records) being longer than 500 characters.

### Current behaviour
- When the DNS records are longer than 500 characters, it fails
- When it fails, subsequent records don't get updated.

### Expected/Desirable behaviour
- Larger limit. 1500 characters? Is there any drawback to that?
- If a DNS record is longer than MAX_LENGTH, truncate and include "[TRUNCATED]" at the end, so the operator knows.
- If an update fails for a particular record, log exception and continue with the next one.

Please, let me know if you need any more info.

**Comment by lez0sec** [comment]
Quick & Dirty Fix for those with the same problem (under your own responsibility. Backup first):

1. Modify ghostwriter/shepherd/models.py to change `max_length` from 500 to 1500

```
    dns_record = models.CharField(
        'DNS Records',
        max_length=1500,
        null=True,
        blank=True,
        help_text='Enter the domain\'s DNS records - leave blank if you '
                  'would prefer to let Ghostwriter fill this in later')
```

2. Find the file with the greatest prefix number `ghostwriter/shepherd/migrations/` and add one to it. In my case `0011_auto_20200123_0726`, so I create a file called `0012_manual_fix_bug.py` with the following contents:
```
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0011_auto_20200123_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns_record',
            field=models.CharField('DNS Records', max_length=1500, null=True, blank=True, help_text='Enter the domain\'s DNS records - leave bla$
        ),
    ]
```

Note that `0011_auto_20200123_0726` must be listed as a dependency

Run
`docker-compose -f local.yml run --rm django python manage.py migrate`

**Comment by chrismaddalena** [comment]
@lez0sec Thank you for reporting this! Sorry it has taken me so long to acknowledge this.

There is a potential drawback to increasing the size limit, but it's negligible. Per Django docs, it is best to use a max length of 255 to ensure compatibility with different database backends. If you wanted to switch to a MysQL backend `VARCHAR` fields would be limited to 255 characters, so Django recommends using that as an upper limit. Of course, the current `max_length` value is 500, so we threw that compatibility out the window. The 500 limit is also arbitrary. I set it to 255 out of habit, but had the same issue as you. I doubled it and rounded to 500, but I looked into this more and there's a better way.

Ghostwriter uses PostgreSQL which has no upper limit on character length. Use of `max_length` also depends on if the field if `CharField` or `TextField`. Most of the fields are set to `CharField` because they expect a few words at most (e.g., a domain category) – this is like declaring a field as `VARCHAR`. It's good practice to set a maximum length for `CharField`\`VARCHAR` (or so I've always been told), but it's _not_ necessary for PostgreSQL. Also, PostgreSQL states there is no performance difference between the different character datatypes (postgresql.org/docs/9.0/datatype-character.html).

Going a step further, `CharField` is inappropriate for the DNS records field. It can receive so much text that it should be a `TextField`. From Django's docs for `CharField` states:

>A string field, for small- to large-sized strings.
> For large amounts of text, use TextField.

I've modified `dns_record` to be ` TextField` with no `max_length` set. This is a big improvement all around. I'm glad you mentioned this so I had a reason to dig into this now almost two-year-old code. It just shouldn't have been setup like this to begin with 😄 Thanks!

I'll add a database model review to my TODO list for some day soon. I'll see if there are any other fields that could be tweaked to avoid issues like this one.

Also, if you edit a database model in the future, you can automatically generate the migrations by running the following commands. You'll also need to do this after you pull this latest code.

`docker-compose -f local.yml run --rm django python manage.py makemigrations`

Then perform the migration with:

`docker-compose -f local.yml run --rm django python manage.py migrate`

You'll get output like this:

```
Migrations for 'shepherd':
  ghostwriter/shepherd/migrations/0012_auto_20200616_0441.py
    - Alter field dns_record on domain

...

Running migrations:
  Applying shepherd.0012_auto_20200616_0441... OK
```
